apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "neos-pdfreader.fullname" . }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: neos-pdf=ghcr.io/naborisk/neos-pdfreader-backend
    argocd-image-updater.argoproj.io/neos-pdf.update-strategy: latest
