apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neos-pdfreader.fullname" . }}
  labels:
    app: {{ include "neos-pdfreader.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "neos-pdfreader.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "neos-pdfreader.fullname" . }}
    spec:
      containers:
        - name: {{ include "neos-pdfreader.fullname" . }}
          image: ghcr.io/naborisk/neos-pdfreader-backend:main
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
