apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neos-pdf.fullname" . }}
  labels:
    app: {{ include "neos-pdf.fullname" . }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/naborisk/neos-pdfreader-backend:main
spec:
  selector:
    matchLabels:
      app: {{ include "neos-pdf.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "neos-pdf.fullname" . }}
    spec:
      containers:
        - name: {{ include "neos-pdf.fullname" . }}
          image: ghcr.io/naborisk/neos-pdfreader-backend:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
