apiVersion: v1
kind: Service
metadata:
  name: {{ include "neos-pdfreader.fullname" . }}
spec:
  selector:
    app: {{ include "neos-pdfreader.fullname" . }}
  ports:
    - port: {{ .Values.port }}
      targetPort: 3000
  type: LoadBalancer
