apiVersion: v1
kind: Service
metadata:
  name: {{ include "neos-pdf.fullname" . }}
spec:
  selector:
    app: {{ include "neos-pdf.fullname" . }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: LoadBalancer
