apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "elysia-hello.fullname" . }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: elysia-hello={{ .Values.image.name }}:{{ .Values.image.tag }}
    argocd-image-updater.argoproj.io/elysia-hello.update-strategy: digest
