apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/fullstack-todo-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: PORT
              value: "3001"
          image: backend
          name: backend
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
      restartPolicy: Always
