apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/fullstack-todo-default: 'true'
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: todo
            - name: POSTGRES_PASSWORD
              value: postgres
          image: postgres
          name: db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
      restartPolicy: Always
