apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    ## Here we are telling that any request coming to this ingress will
    ## reach the Service without the Prefix
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ## Name of the IngressClass we are going to use
  ingressClassName: nginx
  rules:
    ## Here we apply the routing rules for our initial ingress version
    - host: { { .Values.host } }
      http:
        paths:
          ## Every request coming into our Cluster IP will be redirected internally
          ## to the Service with the name "backend" on port 5678 and because of the
          ## nginx.ingress.kubernetes.io/rewrite-target defined above, it will
          ## automatically remove the "/backend" from the path.
          ## ie. 51.158.57.177/backend -> (backend service internal address):5678/
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
