apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shell-bot-concurrent.fullname" . }}
  labels:
    app: {{ include "shell-bot-concurrent.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "shell-bot-concurrent.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "shell-bot-concurrent.fullname" . }}
    spec:
      containers:
        - name: {{ include "shell-bot-concurrent.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SECRET_KEY
              value: {{ .Values.env.SECRET_KEY }}
            - name: CONCURRENT_HOST
              value: {{ .Values.env.CONCURRENT_HOST }}
            - name: POST_STREAM
              value: {{ .Values.env.POST_STREAM }}
